### ISSUE TITLE
[Feature] Iterator interface for cap_map

### ISSUE THREAD

**Issue by harsath** [harsath/cap-containers#21]
Check the `cap_vector`'s iterator interface for a reference. We need to do something like that, but for `cap_map`.

It is pretty straightforward since we just need to iterate over the linked list linearly.

**EDIT:**
We do not store the actual elements on the Iterator. An Iterator is just an abstraction over a pointer(we are mimicking C++ STL's Iterator interface). Since it's just an abstraction over pointers, In this specific case(`cap_map`), since in the implementation we use skip-list version to store the key-value pair, all the elements are available on the index `0` of the `_forward`, we only need to traverse the singly linked list like we normally traverse one. Tests must be written once implemented to deal with most of the common cases. It should also support some operations that `cap_vector`'s Iterator interface supports, with the same style.

To name a few:
* `cap_map_iterator_init`
* `cap_map_iterator_increment`
* `cap_map_iterator_decrement`
* `cap_map_iterator_next`
* `cap_map_iterator_previous`
* `cap_map_iterator_equals_predicate`
* `cap_map_iterator_begin`
* `cap_map_iterator_end`
* `cap_map_iterator_free`
Since in this case, we only need to traverse a singly linked list(without doing any modifications to the underlying list), all these operations should be pretty straightforward and short. Please follow the coding style/guides on of the previous containers and write the documentation above the function declaration(just like the other ones, in JavaDoc style).

**Comment by sonaljain067** [comment]
I would like to work on this issue.

**Comment by harsath** [comment]
#39 Done!
